### ISSUE TITLE
False positive ng-mocks not in JIT

### ISSUE THREAD

**Issue by jkyoutsey** [ike18t/ng-mocks#1438]
I just upgraded to Angular 13 from Angular 12.

```
Angular CLI: 13.0.4
Node: 14.15.1
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 13.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```

Every test fails with the same error message. Even spec files that have NO ng-mocks in them fail like this:
```
Error: LoadingIndicatorComponent declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely,  ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.
            at node_modules/ng-mocks/cjs/lib/common/error.missing-decorators.js:5:1
            at push.67197.exports.default (node_modules/ng-mocks/cjs/lib/common/core.reflect.body-catch.js:16:1)
            at node_modules/ng-mocks/cjs/lib/common/core.reflect.directive-resolve.js:11:113
            at node_modules/ng-mocks/cjs/lib/common/core.reflect.meta.js:11:1
            at generateTouches (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:136:1)
            at defineTouches (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:169:1)
            at Function.<anonymous> (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:257:1)
            at Function.<anonymous> (node_modules/ng-mocks/cjs/lib/mock-helper/mock-helper.faster-install.js:43:1)
            at src/app/common/loading-indicator/loading-indicator.component.spec.ts:9:9
            at Generator.next (<anonymous>)
```

Here is a sample:
```typescript
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { LoadingIndicatorComponent } from './loading-indicator.component';

describe('LoadingIndicatorComponent', () => {
	let component: LoadingIndicatorComponent;
	let fixture: ComponentFixture<LoadingIndicatorComponent>;

	beforeEach(async () => {
		await TestBed.configureTestingModule({
			declarations: [LoadingIndicatorComponent]
		}).compileComponents();
		fixture = TestBed.createComponent(LoadingIndicatorComponent);
		component = fixture.componentInstance;
		fixture.detectChanges();
	});

	it('should create', () => {
		expect(component).toBeTruthy();
	});
});
```

I've tried both with and without this line in tests.ts (I didn't have this with Angular 12, so I hadn't added it for 13 either)
`ngMocks.autoSpy('jasmine');`

I'm completely blocked from upgrading to ng 13 since all of my component-based tests are broken.

**Comment by jkyoutsey** [comment]
This is a duplicate of https://github.com/ike18t/ng-mocks/issues/1427

**Comment by satanTime** [comment]
Thanks for reporting. Please subscribe to the issue from the comment above.

**Comment by satanTime** [comment]
[v13.0.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
