### ISSUE TITLE
MockBuilder: RouterModule imported in an AppRoutingModule

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#151]
Hi again,
When I use **MockBuilder** to test an **AppComponent** and that the **RouterModule** is imported from an **AppRoutingModule**.
I get this error : 

`Error: Unexpected value 'undefined' exported by the module 'MockOfAppRoutingModule'`

You can see the error in [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-routing-module).
The code works fine in production.

> _angular.json_
> **Production** :
> projects -> demo -> architect -> build -> options -> main -> `src/main.ts`
> **Testing** :
> projects -> demo -> architect -> build -> options -> main -> `src/main-testing.ts`

Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi, thanks for the report.

I found the issue and fixed it but met another issue, because HelloComponent is mocked, but RouterModule isn't - there's a conflict: original HelloComponent isn't find from router config what is expected.

Might you explain a bit the purpose to keep RouterModule as it is?

**Comment by cdupetit** [comment]
Hi,
I've followed the [angular tutorial](https://angular.io/tutorial/toh-pt5#final-code-review).
I thought that was a best practice.
Best Regards.
Cyril

**Comment by satanTime** [comment]
yes, you can use RoutingModule, but why do you want to keep it not mocked in the test? 
usually everything should be mocked except the testing thing.

**Comment by cdupetit** [comment]
There is two test suite one with _keep AppRoutingModule_ and one with _mocked AppRoutingModule_.
The both failed.
The test suite _keep AppRoutingModule_ is just for study case.
I want to mock everything as possible.

**Comment by cdupetit** [comment]
Hi @satanTime,
I still have an error on this configuration (**AppRoutingModule**) with _ng-mocks v9_ and _ng-mocks v10_.

`Error: Component HelloComponent is not part of any NgModule or the module has not been imported into your module.`

You can see the error in [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-routing-module).
The code works fine in production.

> _angular.json_
> **Production** :
> projects -> demo -> architect -> build -> options -> main -> `src/main.ts`
> **Testing** :
> projects -> demo -> architect -> build -> options -> main -> `src/main-testing.ts`

Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi again, yeah, I guess, I have some ideas and try to fix it on the coming weekend.

Thanks for the code example.

**Comment by satanTime** [comment]
Hi,

might you check https://github.com/ike18t/ng-mocks/pull/159/files#diff-a97222c4901dada70a979186c3df7ec5 and let me know if it works for your tests?

**Comment by cdupetit** [comment]
> Hi,
> 
> might you check https://github.com/ike18t/ng-mocks/pull/159/files#diff-a97222c4901dada70a979186c3df7ec5 and let me know if it works for your tests?

Hi @satanTime,
I don't know how to merge your changes.
Best regards.

**Comment by satanTime** [comment]
Good, let's try like before: [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/4906746/ng-mocks.zip)

**Comment by cdupetit** [comment]
The test are done but I've this error message in the console :

```
console.error
    Error during cleanup of component {
      component: AppComponent {
        _expandTime: 20,
        _snackBarDuration: 20,
        title: Title { _doc: [Document] },
        router: Router {
          setupNavigations: [Function],
          resetRootComponentType: [Function],
          getTransition: [Function],
          setTransition: [Function],
          initialNavigation: [Function],
          setUpLocationChangeListener: [Function],
          getCurrentNavigation: [Function],
          triggerEvent: [Function],
          resetConfig: [Function],
          ngOnDestroy: [Function],
          dispose: [Function],
          createUrlTree: [Function],
          navigateByUrl: [Function],
          navigate: [Function],
          serializeUrl: [Function],
          parseUrl: [Function],
          isActive: [Function],
          removeEmptyProps: [Function],
          processNavigations: [Function],
          scheduleNavigation: [Function],
          setBrowserUrl: [Function],
          resetStateAndUrl: [Function],
          resetUrlToCurrentUrlTree: [Function],
          events: [Observable]
        },
        store: MockStore {
          _isScalar: false,
          actionsObserver: [ActionsSubject],
          reducerManager: [MockReducerManager],
          source: [MockState],
          'state$': [MockState],
          initialState: {},
          selectors: Map(0) {},
          lastState: {},
          'scannedActions$': [Observable]
        },
        swUpdate: SwUpdate {
          checkForUpdate: [Function],
          activateUpdate: [Function],
          isEnabled: false,
          available: [Observable]
        },
        matSnackBar: MatSnackBar {
          openFromComponent: [Function],
          openFromTemplate: [Function],
          open: [Function],
          dismiss: [Function],
          ngOnDestroy: [Function],
          _attachSnackBarContainer: [Function],
          _attach: [Function],
          _animateSnackBar: [Function],
          _createOverlay: [Function],
          _createInjector: [Function]
        },
        viewService: ViewService {
          isPublic: [Function],
          canAccess: [Function],
          viewRoleList: [Function],
          viewList: [Function]
        },
        notificationService: NotificationService {
          notify: [Function],
          'notification$': [Observable]
        },
        overlayContainer: OverlayContainer {
          ngOnDestroy: [Function],
          getContainerElement: [Function],
          _createContainer: [Function]
        },
        reload: false,
        loading: true,
        production: false,
        name: 'kipunji',
        version: '10.0.0',
        year: 2020,
        themes: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
        '_destroyed$': Subject {
          _isScalar: false,
          observers: [Array],
          closed: false,
          isStopped: false,
          hasError: false,
          thrownError: null
        },
        'expand$': Store {
          _isScalar: false,
          actionsObserver: [ActionsSubject],
          reducerManager: [MockReducerManager],
          source: [Store],
          operator: [DistinctUntilChangedOperator]
        },
        'loggedIn$': Store {
          _isScalar: false,
          actionsObserver: [ActionsSubject],
          reducerManager: [MockReducerManager],
          source: [Store],
          operator: [DistinctUntilChangedOperator]
        },
        sidenav: MatSidenav {
          __ngMocksMock: true,
          openedChange: [EventEmitter_],
          _openedStream: [EventEmitter_],
          openedStart: [EventEmitter_],
          _closedStream: [EventEmitter_],
          closedStart: [EventEmitter_],
          onPositionChanged: [EventEmitter_],
          __mockedOutputs: [Array],
          _takeFocus: [Function],
          _restoreFocus: [Function],
          _isFocusWithinDrawer: [Function],
          ngAfterContentChecked: [Function],
          ngOnDestroy: [Function],
          open: [Function],
          close: [Function],
          _closeViaBackdropClick: [Function],
          toggle: [Function],
          _setOpen: [Function],
          _updateFocusTrapState: [Function],
          _animationStartListener: [Function],
          _animationDoneListener: [Function],
          fixedInViewport: [Getter/Setter],
          fixedTopGap: [Getter/Setter],
          fixedBottomGap: [Getter/Setter],
          position: [Getter/Setter],
          mode: [Getter/Setter],
          disableClose: [Getter/Setter],
          autoFocus: [Getter/Setter],
          opened: [Getter/Setter],
          _width: [Getter/Setter],
          __ngMocksMockControlValueAccessor: true,
          __simulateChange: [Function (anonymous)],
          __simulateTouch: [Function (anonymous)],
          __simulateValidatorChange: [Function (anonymous)],
          setDisabledState: [Function (anonymous)],
          validate: [Function (anonymous)],
          writeValue: [Function (anonymous)],
          __hide: [Function (anonymous)],
          __render: [Function (anonymous)]
        },
        'viewList$': Observable { _isScalar: false, _subscribe: [Function (anonymous)] }
      },
      stacktrace: TypeError: view.disposables[i] is not a function
          at destroyView (E:\cdupetit\Documents\VS.Code\slan.gitlab\slan\packages\core\src\view\view.ts:525:26)
          at callViewAction (E:\cdupetit\Documents\VS.Code\slan.gitlab\slan\packages\core\src\view\view.ts:644:7) {
        ngDebugContext: DebugContext_ {
          view: [Object],
          nodeIndex: 75,
          nodeDef: [Object],
          elDef: [Object],
          elView: [Object]
        },
        ngErrorLogger: [Function: bound ]
      }
    }

      at ../../packages/core/testing/src/test_bed.ts:336:17
          at Array.forEach (<anonymous>)
      at TestBedViewEngine.resetTestingModule (../../packages/core/testing/src/test_bed.ts:332:26)
      at Function.TestBedViewEngine.resetTestingModule (../../packages/core/testing/src/test_bed.ts:131:29)
      at ../../packages/core/testing/src/before_each.ts:25:13
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
```

**Comment by satanTime** [comment]
ouch :) do you get it with the same stackblitz?

**Comment by cdupetit** [comment]
I don't know how to import your zip in stackblitz

**Comment by satanTime** [comment]
Usually I download a project from stackblitz and run it locally. Later today I'll check if I can get the error.

**Comment by satanTime** [comment]
Looks like the issue isn't much related to ng-mocks: https://github.com/angular/angular/issues/17013

**Comment by cdupetit** [comment]
The test are good but same console error. But it's not due to the patch. It give the same result with the regular version 10.0.0

```
ERROR: 'Error during cleanup of component', Object{component: AppComponent{title: 'ng-routing-test', __ngContext__: [..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...]}, stacktrace: TypeError: lCleanup[useCaptureOrSubIdx] is not a function
TypeError: lCleanup[useCaptureOrSubIdx] is not a function
    at removeListeners (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9062:1)
    at cleanUpView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9018:1)
    at destroyViewTree (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8812:1)
    at destroyLView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8970:1)
    at RootViewRef.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9704:1)
    at ComponentRef$1.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22341:1)
    at ComponentFixture.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:322:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2039:1
    at Array.forEach (<anonymous>)
    at TestBedRender3.destroyActiveFixtures (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2037:1)}
Chrome 83.0.4103.116 (Windows 7): Executed 1 of 3 SUCCESS (0 secs / 0.237 secs)
ERROR: 'Error during cleanup of component', Object{component: AppComponent{title: 'ng-routing-test', __ngContext__: [..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...]}, stacktrace: TypeError: lCleanup[useCaptureOrSubIdx] is not a function
TypeError: lCleanup[useCaptureOrSubIdx] is not a function
    at removeListeners (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9062:1)
    at cleanUpView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9018:1)
    at destroyViewTree (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8812:1)
    at destroyLView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8970:1)
    at RootViewRef.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9704:1)
    at ComponentRef$1.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22341:1)
    at ComponentFixture.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:322:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2039:1
    at Array.forEach (<anonymous>)
ERROR: 'Error during cleanup of component', Object{component: AppComponent{title: 'ng-routing-test', __ngContext__: [..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...]}, stacktrace: TypeError: lCleanup[useCaptureOrSubIdx] is not a function
TypeError: lCleanup[useCaptureOrSubIdx] is not a function
    at removeListeners (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9062:1)
    at cleanUpView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9018:1)
    at destroyViewTree (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8812:1)
    at destroyLView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8970:1)
    at RootViewRef.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9704:1)
    at ComponentRef$1.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22341:1)
    at ComponentFixture.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:322:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2039:1
    at Array.forEach (<anonymous>)
    at TestBedRender3.destroyActiveFixtures (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2037:1)}
Chrome 83.0.4103.116 (Windows 7): Executed 2 of 3 SUCCESS (0 secs / 0.315 secs)
ERROR: 'Error during cleanup of component', Object{component: AppComponent{title: 'ng-routing-test', __ngContext__: [..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...]}, stacktrace: TypeError: lCleanup[useCaptureOrSubIdx] is not a function
TypeError: lCleanup[useCaptureOrSubIdx] is not a function
    at removeListeners (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9062:1)
    at cleanUpView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9018:1)
    at destroyViewTree (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8812:1)
    at destroyLView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8970:1)
    at RootViewRef.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9704:1)
    at ComponentRef$1.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22341:1)
    at ComponentFixture.destroy (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:322:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2039:1
    at Array.forEach (<anonymous>)
Chrome 83.0.4103.116 (Windows 7): Executed 3 of 3 SUCCESS (0.518 secs / 0.366 secs)
```

**Comment by satanTime** [comment]
Might you create a min project and attach it as a zip here?
I think it can be even a new issue.

**Comment by cdupetit** [comment]
min project: [ng-routing-test](https://github.com/ike18t/ng-mocks/files/4907316/ng-routing-test.zip)

**Comment by satanTime** [comment]
Thanks! I'll take a look today / tomorrow

**Comment by satanTime** [comment]
I've created a new issue for that: https://github.com/ike18t/ng-mocks/issues/162

**Comment by satanTime** [comment]
Good news, I found the issue and fixed it. Next hours I'll release a new version with the fix.
