### ISSUE TITLE
Error being thrown when using @angular v6.1.8 & v6.1.9

### ISSUE THREAD

**Issue by ike18t** [ike18t/ng-mocks#21]
Failed: Can't resolve all parameters for ApplicationModule: (?).
	Error: Can't resolve all parameters for ApplicationModule: (?).
	    at syntaxError (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:18194:21)
	    at CompileMetadataResolver._getDependenciesMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:28083:39)
	    at CompileMetadataResolver._getTypeMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27976:30)
	    at CompileMetadataResolver.getNgModuleMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27844:28)
	    at CompileMetadataResolver.getNgModuleSummary (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27654:39)
	    at /tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27768:55
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27756:53)
	    at CompileMetadataResolver.getNgModuleSummary (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27654:39)
	    at /tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27768:55
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27756:53)
	    at CompileMetadataResolver.getNgModuleSummary (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27654:39)
	    at /tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27768:55
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27756:53)
	    at CompileMetadataResolver.getNgModuleSummary (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27654:39)
	    at /tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27741:59
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:27719:53)
	    at JitCompiler._loadModules (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:41028:55)
	    at JitCompiler._compileModuleAndAllComponents (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:41016:40)
	    at JitCompiler.compileModuleAndAllComponentsAsync (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:40975:41)
	    at CompilerImpl.compileModuleAndAllComponentsAsync (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:10506:35)
	    at TestingCompilerImpl.compileModuleAndAllComponentsAsync (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:11305:35)
	    at TestBed.compileComponents (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:9894:35)
	    at Function.TestBed.compileComponents (/tmp/karma-typescript-bundle-5704DW9kFrAmtZ6Z.js:9753:71)
	    at UserContext.<anonymous> (lib/mock-component/mock-component.spec.ts:56:5 <- lib/mock-component/mock-component.spec.js:55:14)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:106:39)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:125:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	    at Zone.runGuarded (node_modules/zone.js/dist/zone.js:151:47)
	    at runInTestZone (node_modules/zone.js/dist/async-test.js:234:29)
	    at UserContext.<anonymous> (node_modules/zone.js/dist/async-test.js:168:17)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	    at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	    at runInTestZone (node_modules/zone.js/dist/jasmine-patch.js:142:34)
	    at UserContext.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:158:20)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/jasmine-patch.js:250:42)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/jasmine-patch.js:250:42)
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	    at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	    at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)+

**Comment by ike18t** [comment]
Looks like this is a known issue:
https://github.com/angular/angular/issues/26128

The fix is to include the following in your test shim:
```
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
```
